# Generated by Django 4.2.4 on 2023-10-29 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_owner', models.CharField(default='null', max_length=255)),
                ('shopname', models.CharField(default='null', max_length=255)),
                ('location', models.CharField(default='null', max_length=255)),
                ('phone_no', models.CharField(default='null', max_length=255)),
                ('email', models.CharField(default='null', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='null', max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(default='null', max_length=100)),
                ('quantity', models.CharField(default=1, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('category', models.CharField(max_length=100)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.shop')),
            ],
        ),
    ]
